# Generated by Django 3.2.8 on 2021-10-23 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_assignedquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztask',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiztask',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Qeustions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.AlterModelOptions(
            name='userquizinfo',
            options={'verbose_name': 'User Quiz Info', 'verbose_name_plural': 'Users Quiz Info'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='set_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='AssignedQuiz',
        ),
        migrations.DeleteModel(
            name='QuizTask',
        ),
    ]
