# Generated by Django 3.2.8 on 2021-10-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='opt_4',
        ),
    ]
