# Generated by Django 3.2.8 on 2021-10-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quiz_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='due_date',
            field=models.DateField(),
        ),
    ]
