# Generated by Django 3.2.8 on 2021-10-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_quiz_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='due_date',
        ),
    ]
