# Generated by Django 3.2.8 on 2021-10-30 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_quiz_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 16, 4, 17, 814485, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
