# Generated by Django 3.2.8 on 2021-11-14 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_quiz_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizinfo',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
